interface Env {
  DB: D1Database;
  APP_NAME?: string;
  B2_APPLICATION_KEY?: string;
  B2_APPLICATION_KEY_ID?: string;
  B2_ALLOWED_MIME_TYPES?: string;
  B2_UPLOAD_MAX_BYTES?: string;
  GOOGLE_CLOUD_TRANSLATION_API_KEY?: string;
  SERVICE_PUBLIC_URL?: string;
  NO_TORSION_CORRECTION_FORM_ID?: string;
  NO_TORSION_CORRECTION_SUBMIT_TARGET?: string;
  NO_TORSION_FORM_DRY_RUN?: string;
  NO_TORSION_FORM_ID?: string;
  NO_TORSION_FORM_PROTECTION_MAX_AGE_MS?: string;
  NO_TORSION_FORM_PROTECTION_MIN_FILL_MS?: string;
  NO_TORSION_FORM_SUBMIT_TARGET?: string;
  NO_TORSION_MEDIA_SUBMIT_TARGET?: string;
  MOTHER_FORM_SYNC_BATCH_SIZE?: string;
  MOTHER_FORM_SYNC_TIMEOUT_MS?: string;
  NO_TORSION_SITE_URL?: string;
  MOTHER_REPORT_URL?: string;
  MOTHER_REPORT_TIMEOUT_MS?: string;
  DATABACK_EXPORT_MIN_INTERVAL_MS?: string;
  DEBUG_MOD?: string;
  TRANSLATION_PROVIDER_TIMEOUT_MS?: string;
}
